### ISSUE TITLE
有完没完？搞这个有意吗？

### ISSUE THREAD

**Issue by Mywayking** [995icu/995ICU.github.io#11]
没事就起哄。真正的程序员还能打几年代码？这时候不多挣钱，什么时候？

**Comment by playGoaway** [comment]
就怕你到时候累垮自己

**Comment by qizhai27** [comment]
996这种风气下，程序员自然没有几年好干的，要么死要么放弃而已，正常的工作节奏怎么就不能干很多年呢？

**Comment by 996zhang** [comment]
钱给够,二话不说

**Comment by ooooiso** [comment]
对了

**Comment by qizhai27** [comment]
程序员是青春饭，本身就非常不健康和不持续，而996，你就注定是青春饭

**Comment by c2ding** [comment]
哈哈哈，看看就好。ICU真不是人呆的地方。

**Comment by Mywayking** [comment]
> 没事就起哄。真正的程序员还能打几年代码？这时候不多挣钱，什么时候？
